config/routes.rb
PolarisManage::Application.routes.draw do
  resources :promotions do
    get "search", on: :collection
    post "delete_promotion", to: "promotions#delete_promotion", on: :collection
    post "get_promotions_report", on: :collection
    post "download_csv", on: :collection
    post "change_data", on: :collection
    get "promotion_table", on: :collection
  end
  resources :users do
    get "change_lang", on: :collection
    post "get_users_list", on: :collection
    get "search", on: :collection
    post "enable_disable_user", on: :collection
    post "change_company_list", on: :collection
  end
  resources :roles
  resources :conversions do
    get "get_tag", on: :member
    post "change_current_id", on: :collection
  end
  resources :clients do
    post "del_client", to: "clients#del_client", on: :collection
    post "get_promotions_list", on: :collection
  end
  resources :agencies do
    post "get_agencies_list", on: :collection
  end
  resources :sessions, only: [:new, :create] do
    post "resend_password", on: :collection
  end
  match "/signin",  to: "sessions#new"
  match "/signout", to: "sessions#signout"
  root to: "clients#index"
  resources :accounts, only: [:new, :create, :edit, :update] do
    post "change_medias_list", on: :collection
  end
  resources :click_logs, only: [:index] do
    post "get_logs_list", on: :collection
    post "download_csv", on: :collection
    post "change_accounts_list", on: :collection
  end
  resources :conversion_promotion_logs, only: [:index] do
    post "get_conversion_logs_list", on: :collection 
    post "download_csv", on: :collection
    post "change_accounts_list", on: :collection
  end
  resources :url_settings do
    post "get_urls_list", on: :collection
    post "download_csv", on: :collection
    get "download_template", on: :collection
  end
  resources :background_jobs do
    get "upload", on: :collection
    get "download", on: :collection
    get "inprogress", on: :collection
    post "notification", on: :collection
    get "download_file", on: :collection
    post "kill_job", to: "background_jobs#kill_job", on: :collection
  end
  resources :imports
  mount Resque::Server, at: '/resque'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]{2,}+\z/i
  VALID_ROMAN_NAME_REGEX = /^[\s!-~]+$/

  attr_accessible :username, :roman_name, :email, :company_id, :role_id,
    :password_flg

  belongs_to :role
  has_many :client_users
  has_one :block_login_user

  validates :username, presence: true, uniqueness: {case_sensitive: false},
    length: {maximum: 255}
  validates :roman_name, presence: true, uniqueness: {case_sensitive: false},
    length: {maximum: 255}
  validates :roman_name, format: {with: VALID_ROMAN_NAME_REGEX},
    if: -> user {user.roman_name.present?}
  validates :email, presence: true, uniqueness: {case_sensitive: false}
  validates :email, format: {with: VALID_EMAIL_REGEX}, length: {maximum: 255},
    if: -> user {user.email.present?}
  validates :company_id, presence: true
  validates :role_id, presence: true
  validates :password_flg, presence: true
 
  scope :order_by_roman_name, ->{order :roman_name}
  scope :active, where(status: Settings.user.active)

  before_save {|user| user.email = email.downcase}
 
  def can_login?
    return false if self.status == Settings.user.deactive
    if self.block_login_user && self.block_login_user.login_fail_num >=
      Settings.login.login_block_number
      if self.block_login_user.block_at_time > 5.minutes.ago
        return false
      else
        return self.remove_block_login
      end
    else
      return true
    end
  end
 
  def update_login_fail
    block = self.block_login_user
    if block
      if block.login_fail_num < Settings.login.login_block_number
        block.login_fail_num += 1
        block.block_at_time = Time.now if block.login_fail_num >=
          Settings.login.login_block_number
        block.save!
      end
    else
      BlockLoginUser.create(user_id: self.id, login_fail_num: 1)
    end
  end

  def toggle_enabled
    self.status = self.active? ? Settings.user.deactive : Settings.user.active
    self.del_client_user if self.deactive?
    self.save!
  end
 
  def remove_block_login
    self.block_login_user.login_fail_num = 0
    self.block_login_user.block_at_time = nil
    self.block_login_user.save
  end
 
  def valid_attribute?(attribute_name)
    self.valid?
    self.errors[attribute_name].blank?
  end

  def active?
    self.status == Settings.user.active
  end

  def deactive?
    self.status == Settings.user.deactive
  end
 
  def super?
    self.role_id == Settings.role.SUPER
  end
 
  def client?
    self.role_id == Settings.role.CLIENT
  end
 
  def agency?
    self.role_id == Settings.role.AGENCY
  end
 
  def del_client_user
    self.client_users.each do |client_user|
      client_user.update_attributes!(del_flg: Settings.client_user.deleted)
    end
  end
end

app/controllers/users_controller.rb
require 'action_view'
class UsersController < ApplicationController
  include ActionView::Helpers::SanitizeHelper
  before_filter :signed_in_user
  before_filter :must_super
  before_filter :must_not_himself, only: [:edit, :update]
  
  def index
  end

  def show
  end
  
  def new
    @user = User.new
    @prevent = "0"
  end
  
  def create
    params[:user][:roman_name] = sanitize(params[:user][:roman_name])
    params[:user][:username] = sanitize(params[:user][:username])
    @user = User.new(params[:user])
    @prevent = "1"
    @user.password = SecureRandom.urlsafe_base64(6)
    @user.create_user_id = current_user.id
    if @user.valid?
      role = Role.find(params[:user][:role_id])
      if role.id == 2
        company = Client.find(params[:user][:company_id])
      else
        company = Agency.find(params[:user][:company_id])
      end
      @user.save!
      if @user.client?
        ClientUser.create(client_id: @user.company_id, user_id: @user.id)
      end
      flash[:success] = I18n.t("user.flash_messages.success")
      if @user.password_flg == "1"
        job_id = SendMail.create(user: @user, password: @user.password)
      end
      redirect_to new_user_path
    else
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
    @prevent = "0"
  end
  
  def update
    @user = User.find(params[:id])
    @prevent = "1"
    @user.update_user_id = current_user.id
    params[:user][:roman_name] = sanitize(params[:user][:roman_name])
    params[:user][:username] = sanitize(params[:user][:username])
    @user.attributes = params[:user]
    if @user.valid?
      if (@user.active? && params[:deactive] == "on") || (!@user.active? && !params[:deactive])
        @user.toggle_enabled
      else
        @user.save!
      end
      flash[:success] = I18n.t("user.flash_messages.update")
      redirect_to users_path
    else
      render :edit
    end
  end
  
  def get_users_list
    rows = get_rows(User.order('role_id').page(params[:page]).per(params[:rp]))
    render json: {page: params[:page], total: User.count, rows: rows}
  end

  def change_company_list
    model = params[:model].constantize
    if model == Client
      render json: model.active.all
    else
      render json: model.all
    end
  end

  private
  def get_rows users
    rows = Array.new
    users.each do |user|
      company = ""
      if user.client?
        if client = Client.find_by_id(user.company_id)
          company = client.client_name
        end
      else
        if agency = Agency.find_by_id(user.company_id)
          company = agency.agency_name
        end
      end
      link = user.id == current_user.id ?
         "" : "<a href='users/#{user.id}/edit'>#{view_context.image_tag("/assets/img_edit.png")}</a>"
      rows << {id: user.id, cell: {
               link: link, roman_name: "<div title='#{user.roman_name}'>" + user.roman_name + "</div>",
               username: "<div title='#{user.username}'>" + user.username + "</div>",
               company: "<div title='#{company}'>" + company,
               email: "<div title='#{user.email}'>" + user.email + "</div>",
               role: "<div title='#{user.role.role_name}'>" + user.role.role_name + "</div>"}}
    end
    rows
  end
  
  def must_not_himself
    redirect_to users_path if current_user.id == params[:id].to_i
  end
end

app/views/users/edit.html.erb
<% provide(:title, I18n.t("user.title.edit")) %>
<script type="text/javascript">
$(function(){
	prevent_change = "<%= @prevent %>";
	$(".prevent_change").change(function(){
		prevent_change = "1"
	})
})
</script>
<%= render "layouts/prevent_change_page_edit" %>
<%= stylesheet_link_tag "css/users_new" %>
<%= stylesheet_link_tag "css/common" %>
<%= flash[:success] if flash[:success] %>
<div id="user_form">
  <p class="h2"><%= I18n.t("user.crumb_edit") %></p>
  <%= form_for(@user) do |f| %>
      <table>
        <tbody>
        <tr>
          <th><div style="width: 190px;"><%= f.label I18n.t("user.username") %></div></th>
          <td colspan="2"><%= f.text_field :username, maxlength: 255, style: "width: 280px",tabindex: 1, class: "prevent_change" %></td>
        </tr>
        <tr>
          <th><div style="width: 190px;"><%= f.label I18n.t("user.roman_name") %></div></th>
          <td colspan="2"><%= f.text_field :roman_name, maxlength: 255, style: "width: 280px",tabindex: 2, class: "prevent_change" %></td>
        </tr>
        <tr>
          <th><div style="width: 190px;"><%= f.label I18n.t("user.email") %></div></th>
          <td colspan="2"><%= f.text_field :email, maxlength: 255, style: "width: 280px",tabindex: 3, class: "prevent_change" %></td>
        </tr>
        <tr>
          <th><div style="width: 190px;"><%= f.label I18n.t("user.role.label") %></div></th>
          <td colspan="2">
            <%= text_field_tag :role_id, @user.role.role_name, disabled: true, style: "width: 280px;" %>
          </td>
        </tr>
        <tr>
          <th><div style="width: 190px;"><%= f.label I18n.t("user.company_name") %></div></th>
          <td colspan="2">
            <% if @user.client? %>
                <%= text_field_tag :company_id, Client.find(@user.company_id).client_name, disabled: true, style: "width: 280px;" %>
            <% else %>
                <%= text_field_tag :company_id, Agency.find(@user.company_id).agency_name, disabled: true, style: "width: 280px;" %>
            <% end %>
        </tr>
        <tr>
          <th><div style="width: 190px;"><%= f.label I18n.t("user.password.label") %></div></th>
          <td colspan="2">*******************</td>
        </tr>
        <tr>
          <th><div style="width: 190px;"><%= f.label I18n.t("user.password_notification.label") %></div></th>
          <td style="width: 220px;"><%= f.radio_button :password_flg, "0", disabled: true %> <%= f.label I18n.t("user.password_notification.not_notified") %></td>
          <td style="width: 160px;"><%= f.radio_button :password_flg, "1", disabled: true %> <%= f.label I18n.t("user.password_notification.to_notified") %></td>
        </tr>
        <tr>
          <th><div style="width: 190px;"><%= f.label I18n.t("user.disabled.label") %></div></th>
          <td>
              <% if @user.status == Settings.user.deactive %>
                  <input type="checkbox" id = "disable_button" checked="checked" name="deactive" tabindex= "4" class="prevent_change">
              <% else %>
                  <input type="checkbox" id = "disable_button" name="deactive" tabindex= "4" class="prevent_change">
              <% end %><%= I18n.t("user.disabled.disable") %>
          </td>
        </tr>
        </tbody>
      </table>
      <div class="submit_area">
        <input type="image" id="btn_submit" src="/assets/btn_done.gif" tabindex= "5">
        <%= link_to image_tag("/assets/btn_cancel.gif",align: "right", alt: "キャンセル", tabindex:6), users_path %>
      </div>
      </form>
  <% end %>
</div>

<div style='display:none'>
	<div id="disabled">
		<p class="del_message" style="margin-top:20px;">
			【注意】下記、ユーザーを無効にしようとしています。</br>
			このユーザーではログイン出来なくなってしまいますが、</br>
			問題ないでしょうか。</br>
			-----------------------------------------------</br>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ユーザー名&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <%= short_ja_name(@user.username) %></br>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;メールアドレス&nbsp;&nbsp;: <%= @user.email %></br>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;権限&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ：<%= @user.role.role_name %></br>
			-----------------------------------------------</br>
		</p>
	</div>
	<div id="enabled">
		<p class="del_message" style="margin-top:20px;">
			【注意】下記、ユーザーの無効化を削除しようとしています。</br>
			このユーザーでログインが出来るようになりますが、</br>
			問題ないでしょうか。</br>
			-----------------------------------------------</br>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ユーザー名&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <%= short_ja_name(@user.username) %></br>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;メールアドレス&nbsp;&nbsp;: <%= @user.email %></br>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;権限&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ：<%= @user.role.role_name %></br>
			-----------------------------------------------</br>
		</p>
	</div>
</div>
<script type="text/javascript">
	$(function(){
		check = $("#disable_button").is(':checked')? true : false;
		$(".ok_popup").click(function(){
			$(".edit_user").submit();
		})
		
		$("#btn_submit").click(function(e){
			e.preventDefault();
			checked = $("#disable_button").is(':checked')? true : false;
			if (check != checked){
				if (checked){
					$.confirm({
			            'message'	: $("#disabled").html(),
			            'buttons'	: {
			                "<%= I18n.t('popup.cancel') %>"	: {
			                    'class'	: 'popup_no',
			                    'action': function(){
			                    	$("#disable_button").attr("checked",check);
			                    }	
			                },
			                "<%= I18n.t('popup.disable') %>"	: {
			                    'class'	: 'popup_yes',
			                    'action': function(){
			                        $(".edit_user").submit();
			                    }
			                },
			            }
        			});
				}else{
					$.confirm({
			            'message'	: $("#enabled").html(),
			            'buttons'	: {
			                "<%= I18n.t('popup.cancel') %>"	: {
			                    'class'	: 'popup_no',
			                    'action': function(){
			                    	$("#disable_button").attr("checked",check);
			                    }	
			                },
			                "<%= I18n.t('popup.enable') %>"	: {
			                    'class'	: 'popup_yes',
			                    'action': function(){
			                        $(".edit_user").submit();
			                    }
			                },
			            }
        			});
				}
			}else{
				$(".edit_user").submit();
			}
		})
	})
</script>

app/views/users/index.html.erb
<% provide(:title, I18n.t("user.title.list")) %>
<%= stylesheet_link_tag "css/user2", :media => "all" %>
<%= stylesheet_link_tag "css/common", :media => "all" %>
<% if flash[:success] %>
  <div><%= flash[:success] %></div>
<% end %>
<%= link_to raw("<img src='/assets/btn_user_regist.gif' >"), "javascript:void(0)", class: "new_agency",onclick: "ajaxCommon('#{new_user_path}', '', '', '','#inner')" %>
<table style="display:none" class="newTable04 fixTable d-none"></table>
<script type="text/javascript">
	$(".newTable04").flexigrid({
		url: "<%= get_users_list_users_path %>",
        optionGet : "7",
        editOption : true,
        deleteOption : true,

        resizable : false,
        striped : true,
		dataType: 'json',
		colModel : [
    {display: '', name : 'link', width : '60', sortable : false, align: 'center'},
    {display: '<%= I18n.t("user.user_table.roman_name")%>', name : 'roman_name', width : 'auto', sortable : false, align: 'left'},
	  {display: '<%= I18n.t("user.user_table.username")%>', name : 'username', width : 'auto', sortable : false, align: 'left'},
    {display: '<%= I18n.t("user.user_table.email")%>', name : 'email', width : 'auto', sortable : false, align: 'left'},
    {display: '<%= I18n.t("user.user_table.company_name")%>', name : 'company', width : 'auto', sortable : false, align: 'left'},
    {display: '<%= I18n.t("user.user_table.role")%>', name : 'role', width : 'auto', sortable : false, align: 'center'}
			],
		usepager: true,
		useRp: true,
		rp: 10,
		showTableToggleBtn: true,
		height: 300,
        pagetext: "<%= I18n.t("Page") %>",
        outof: "<%= I18n.t("of") %>"
	});
</script>
<script>
    $(window).resize(function() {
        tableResize();
    });

</script>

app/views/users/new.html.erb
<% provide(:title, I18n.t("user.title.add")) %>
<script type="text/javascript">
$(function(){
	prevent_change = "<%= @prevent %>";
	$(".prevent_change").change(function(){
		prevent_change = "1"
	})
})
</script>
<%= render "layouts/prevent_change_page_new" %>
<%= stylesheet_link_tag "css/users_new" %>
<%= stylesheet_link_tag "css/common" %>
<%= flash[:success] if flash[:success] %>
<div id="user_form">
  <p class="h2"><%= I18n.t("user.crumb_add") %></p>
  <%= form_for(@user) do |f| %>
      <table>
        <tbody>
        <tr>
          <th><div style="width: 190px;"><%= f.label t("user.username") %></div></th>
          <td colspan="2"><%= f.text_field :username, maxlength: 255, style: "width: 280px",tabindex: 1, class: "prevent_change" %></td>
        </tr>
        <tr>
          <th><div style="width: 190px;"><%= f.label t("user.roman_name") %></div></th>
          <td colspan="2"><%= f.text_field :roman_name, maxlength: 255, style: "width: 280px",tabindex: 2, class: "prevent_change" %></td>
        </tr>
        <tr>
          <th><div style="width: 190px;"><%= f.label t("user.email") %></div></th>
          <td colspan="2"><%= f.text_field :email, maxlength: 255, style: "width: 280px",tabindex: 3, class: "prevent_change" %></td>
        </tr>
        <tr>
          <th><div style="width: 190px;"><%= f.label t("user.role.label") %></div></th>
          <td colspan="2">
          	<select class="input-text prevent_change" id="user_role_id" name="user[role_id]" tabindex="4" >
          		<option value=""><%= I18n.t("user.role.include_blank") %></option>
          		<% if @user.role_id == 2 %>
					<option value="2" selected >Client</option>
				<% else %>
					<option value="2">Client</option>
				<% end %>
				<% if @user.role_id == 3 %>
					<option value="3" selected>Agency</option>
				<% else %>
					<option value="3">Agency</option>
				<% end %>
				<% if @user.role_id == 1 %>
					<option value="1" selected>Super</option>
				<% else %>
					<option value="1">Super</option>
				<% end  %>
			</select>
			<p><span class="text-validationError"><%= @user.errors[:role_id][0] %></span></p>
          </td>
        </tr> 
        <tr>
          <th><div style="width: 190px;"><%= f.label t("user.company_name") %></div></th>
          <td colspan="2">
          	<% if @user.role_id && !@user.client? %>
          		<%= f.select :company_id, Agency.all.map {|c| [c.name_with_initial, c.id, {'title' => c.agency_name}]}, {include_blank: t("user.company_id.include_blank")}, {:class => 'input-text prevent_change',tabindex: 5} %>
            <% elsif @user.role_id %>
            	<%= f.select :company_id, Client.active.all.map {|c| [c.name_with_initial, c.id, {'title' => c.client_name}]}, {include_blank: t("user.company_id.include_blank")}, {:class => 'input-text prevent_change',tabindex: 5} %>
            <% else %>
            	<%= f.select :company_id, Client.where(id: 0) {|c| [c.name_with_initial, c.id, {'title' => c.client_name}]}, {include_blank: t("user.company_id.include_blank")}, {:class => 'input-text prevent_change',tabindex: 5} %>
            <% end %>
            </td>
        </tr>
        <tr>
          <th><div style="width: 190px;"><%= I18n.t("user.password.label") %></div></th>
          <td colspan="2"><%= I18n.t("user.password.info") %></td>
        </tr>
        <tr>
          <th><div style="width: 190px;"><%= I18n.t("user.password_notification.label") %></div></th>
          <td style="width: 160px;"><%= f.radio_button :password_flg, "0", checked: true, tabindex: 6, class: "prevent_change" %> <%= I18n.t("user.password_notification.not_notified") %></td>
          <td style="width: 160px;"><%= f.radio_button :password_flg, "1", tabindex: 7, class: "prevent_change" %> <%= I18n.t("user.password_notification.to_notified") %></td>
        </tr>
        </tbody>
      </table>
      <div class="submit_area">
        <input type="image" id="btn_submit" src="/assets/btn_done.gif" name="commit" tabindex = "8">

        <p><%= link_to image_tag("/assets/btn_cancel.gif",align: "right", alt: "キャンセル", tabindex:9), users_path %></p>
      </div>
      </form>
  <% end %>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $("#cancel").click(function (e) {
            e.preventDefault();
            location.href = "<%= users_path %>";
        })
        last_choice = $("#user_role_id").val();
        $("#user_role_id").change(function () {
            id = $(this).val();
            if ((id == 1 && last_choice == 3) || (id == 3 && last_choice == 1)) {
                last_choice = id;
                return;
            }
            if (id==""){
            	$("#user_company_id").html("<option value><%= t('user.company_id.include_blank') %></option>");
            	last_choice = id;
            	return;
            }
            last_choice = id;
            name_data = (id == "2") ? "Client" : "Agency";
            $("#user_company_id").attr("disabled","disabled");
            $.ajax({
                type: "POST",
                url: "<%= change_company_list_users_path %>",
                data: "model=" + name_data,
                success: function (data) {
                    $("#user_company_id").html("<option value><%= t('user.company_id.include_blank') %></option>");
                    for (var i = 0; i < data.length; i++) {
                        name = (name_data == "Client") ? data[i].client_name : data[i].agency_name;
                        option = "<option value='" + data[i].id + "' title='" + name + "'>" + sub_ja(name)  + "</option>";
                        $("#user_company_id").append(option);
                    }
                    $("#user_company_id").removeAttr("disabled");
                }
            });
        })
    })
</script>