config/routes.rb
PolarisManage::Application.routes.draw do
  resources :promotions do
    get "search", on: :collection
    post "delete_promotion", to: "promotions#delete_promotion", on: :collection
    post "get_promotions_report", on: :collection
    post "download_csv", on: :collection
    post "change_data", on: :collection
    get "promotion_table", on: :collection
  end
  resources :users do
    get "change_lang", on: :collection
    post "get_users_list", on: :collection
    get "search", on: :collection
    post "enable_disable_user", on: :collection
    post "change_company_list", on: :collection
  end
  resources :roles
  resources :conversions do
    get "get_tag", on: :member
    post "change_current_id", on: :collection
  end
  resources :clients do
    post "del_client", to: "clients#del_client", on: :collection
    post "get_promotions_list", on: :collection
  end
  resources :agencies do
    post "get_agencies_list", on: :collection
  end
  resources :sessions, only: [:new, :create] do
    post "resend_password", on: :collection
  end
  match "/signin",  to: "sessions#new"
  match "/signout", to: "sessions#signout"
  root to: "clients#index"
  resources :accounts, only: [:new, :create, :edit, :update] do
    post "change_medias_list", on: :collection
  end
  resources :click_logs, only: [:index] do
    post "get_logs_list", on: :collection
    post "download_csv", on: :collection
    post "change_accounts_list", on: :collection
  end
  resources :conversion_promotion_logs, only: [:index] do
    post "get_conversion_logs_list", on: :collection 
    post "download_csv", on: :collection
    post "change_accounts_list", on: :collection
  end
  resources :url_settings do
    post "get_urls_list", on: :collection
    post "download_csv", on: :collection
    get "download_template", on: :collection
  end
  resources :background_jobs do
    get "upload", on: :collection
    get "download", on: :collection
    get "inprogress", on: :collection
    post "notification", on: :collection
    get "download_file", on: :collection
    post "kill_job", to: "background_jobs#kill_job", on: :collection
  end
  resources :imports
  mount Resque::Server, at: '/resque'

end

app/models/client.rb
class Client < ActiveRecord::Base
  include ApplicationHelper
  VALID_PHONE_NUMBER_REGEX = /^\+?[0-9]{,15}$/
  # VALID_ROMAN_NAME_REGEX = /^[A-Z_\ \~\!\@\#\$\%\^\&\*\(\)\_\-\+\=\<\,\>\.\;\:\"\'\{\}|\\\?\?\/a-z][A-Za-z_\ \~\!\@\#\$\%\^\&\*\(\)\_\-\+\=\<\,\>\.\;\:\"\'\{\}|\\\?\?\/\-0-9]*$/
  VALID_ROMAN_NAME_REGEX = /^[\s!-~]+$/
  attr_accessible :client_name, :roman_name, :tel, :department_name,
    :contract_flg, :contract_type, :person_charge, :person_sale,
    :create_user_id, :update_user_id, :del_flg, :time_zone

  has_many :client_users
  has_many :promotions

  validates :client_name, presence: true, uniqueness: {case_sensitive: false},
    length: {maximum: 255}
  validates :roman_name, presence: true, uniqueness: {case_sensitive: false},
    length: {maximum: 255}
  validates :roman_name, format: {with: VALID_ROMAN_NAME_REGEX}, if: -> client { client.roman_name.present?}
  validates :tel, presence: true, length: {maximum: 15}
  validates :tel, format: {with: VALID_PHONE_NUMBER_REGEX}, if: -> client { client.tel.present?}
  validates :contract_flg, presence: true
  validates :contract_type, presence: true
  validates :person_charge, presence: true, length: {maximum: 255}
  validates :person_sale, presence: true, length: {maximum: 255}
  validates :time_zone, presence: true, length: {maximum: 3}
  
  scope :active, where(del_flg: "0")
  scope :order_by_roman_name, ->{order :roman_name}
  
  def update_client_users params
    params[:users_id].each do |user_id|
      return false unless User.find_by_id(user_id) 
      if client_user = self.client_users.find_by_user_id(user_id)
      else
         client_user = self.client_users.build(user_id: user_id)
      end
      del_flg = params["del_user_" + user_id] == "on" ? "1" : "0"
      client_user.del_flg = del_flg
      if client_user.valid?
        client_user.save!
      else
        return false
      end
    end
  end
  
  def name_with_initial
    short_ja_name(self.client_name)
  end
end

app/controllers/clients_controller.rb
require 'action_view'
class ClientsController < ApplicationController
  include ActionView::Helpers::SanitizeHelper
  
  before_filter :signed_in_user
  before_filter :must_super_agency, only: [:index, :show]
  before_filter :must_super, only: [:new, :create, :edit, :update, :destroy,
                                    :del_client]
  before_filter :must_deleteable, only: [:show, :edit, :update, :destroy]
  before_filter :load_list_clients, except: [:destroy, :del_client]
  before_filter :get_time_zones, only: [:new, :create, :edit, :update]

  #get all clients sorted by romaji name
  def index
    if @clients.count > 0
      @client = params[:client_id].blank? ? @clients[0] :
        Client.find_by_id(params[:client_id])
      @client = @clients[0] unless @client
    else
      @clients = Array.new
    end
  end

  #get list promotion and paging
  def get_promotions_list
    # get params for paging
    unless params[:id].blank?
      @client_id = params[:id]
    else
      @client_id = @clients[0].id
    end

    rows = Array.new
    rows = get_rows(Promotion.get_by_client(@client_id).active.
      order_id_desc.page(params[:page]).per(params[:rp]), @client_id)
    count = Promotion.get_by_client(@client_id).active.order_by_promotion_name.count

    render json: {page: params[:page], total: count, rows: rows}
  end

  def new
    @client = Client.new
    @prevent = "0"
  end

  def create
    params[:client][:roman_name] = sanitize(params[:client][:roman_name])
    params[:client][:client_name] = sanitize(params[:client][:client_name])
    params[:client][:person_charge] = sanitize(params[:client][:person_charge])
    params[:client][:person_sale] = sanitize(params[:client][:person_sale])
    @client = Client.new(params[:client])
    @prevent = "1"
    @client.create_user_id = current_user.id
    if @client.valid?
      ActiveRecord::Base.transaction do
        @client.save!
        if params[:users_id]
          if !@client.update_client_users(params)
            @error = I18n.t("client.flash_messages.success_error")
            raise ActiveRecord::Rollback
          end
        end
      end
      unless @error
        @error = I18n.t("client.flash_messages.success")
      end
    end
    respond_to do |format|
      format.js
    end
  end

  def edit
    @prevent = "0"
  end

  def update
    params[:client][:roman_name] = sanitize(params[:client][:roman_name])
    params[:client][:client_name] = sanitize(params[:client][:client_name])
    params[:client][:person_charge] = sanitize(params[:client][:person_charge])
    params[:client][:person_sale] = sanitize(params[:client][:person_sale])
    @client.attributes = params[:client]
    @prevent = "1"
    @client.update_user_id = current_user.id
    if @client.valid?
      ActiveRecord::Base.transaction do
        @client.save!
        if params[:users_id]
          if !@client.update_client_users(params)
            @error = I18n.t("client.flash_messages.update_error")
            raise ActiveRecord::Rollback
          end
        end
      end
      unless @error
        @error = I18n.t("client.flash_messages.update")
      end
    end
    respond_to do |format|
      format.js
    end
  end

  private
  def must_deleteable
    @client = Client.find(params[:id])
    redirect_to clients_path if @client.nil? || @client.del_flg == 1
  end

  def get_rows(promotions, client_id)
    rows = Array.new
    promotions.each do |promotion|
      promotion_name = view_context.link_to(promotion.promotion_name,
        "javascript:void(0)",
        class: "edit",
        id: "edit#{index}",
        title: promotion.promotion_name,
        onclick: "ajaxCommon('#{promotions_path(promotion_id: promotion.id,
          client_id: client_id)}', '', '', '','#sidebar,#container')"
      )
      rows << {id: promotion.id, cell: {promotion_name: promotion_name}}
    end
    rows
  end

  def get_time_zones
    @time_zones = Array.new
    time_zones_list = ActiveSupport::TimeZone.all
    @time_zones[0] = time_zones_list[121]
    idx = 1
    time_zones_list.each_with_index do |tz, index|
      if index != 121
        @time_zones[idx] = tz
        idx+=1
      end
    end
    @time_zones
  end

  def load_list_clients
    if current_user.super?
      @clients = Client.active.order_by_roman_name
    elsif current_user.agency?
      @clients = Array.new
      array_client_user = current_user.client_users.active
      array_client_user.each do |client_user|
        @clients << client_user.client
      end
    end
  end
end

app/views/clients/_client_info_edit_form.html.erb
<%= form_for(@client, remote: true) do |f| %>
    <div class="regist_form">
      <table class="client_info">
        <tr>
          <th> <%= f.label t("client.client_name") %></th>
          <td colspan="2"><%= f.text_field :client_name, maxlength: 255, style: "width: 250px", class: "prevent_change" %></td>
        </tr>
        <tr>
          <th><div style="width: 180px;"><%= f.label t("client.roman_name") %></div></th>
          <td colspan="2"><%= f.text_field :roman_name, maxlength: 255, style: "width: 250px", class: "prevent_change" %></td>
        </tr>
        <tr>
          <th><%= f.label t("client.tel") %></th>
          <td colspan="2"> <%= f.text_field :tel, maxlength: 15, style: "width: 250px", class: "prevent_change" %>  </td>
        </tr>
        <tr>
          <th><%= f.label t("client.person_charge") %></th>
          <td colspan="2"><%= f.text_field :person_charge, maxlength: 255, style: "width: 250px", class: "prevent_change" %></td>
        </tr>
        <tr>
          <th><%= f.label t("client.person_sale") %></th>
          <td colspan="2"><%= f.text_field :person_sale, maxlength: 255, style: "width: 250px", class: "prevent_change" %></td>
        </tr>
        <tr>
          <th><%= f.label t("client.contract_flg.label") %></th>
          <td style="width: 150px;"><%= f.radio_button :contract_flg, 0, class: "prevent_change" %> <%= I18n.t("client.contract_type.unrecovered") %></td>
          <td style="width: 150px;"><%= f.radio_button :contract_flg, 1, class: "prevent_change" %> <%= I18n.t("client.contract_type.been_recovered") %></td>
        </tr>
        <tr>
          <th><%= f.label t("client.contract_type.label") %></th>
          <td><div style="width: 200px;"><%= f.radio_button :contract_type, 0, class: "prevent_change" %> <%= I18n.t("client.contract_flg.standard_plan") %></div></td>
          <td><div style="width: 310px;"><%= f.radio_button :contract_type, 1, class: "prevent_change" %> <%= I18n.t("client.contract_flg.premium_plan") %></div></td>
        </tr>
        <tr>
          <th><%= f.label t("client.time_zones") %></th>
          <td colspan="2">
                         <%= f.select(:time_zone, @time_zones.each_with_index.map {|name, index| [name, index+1]}, :prompt => I18n.t("client.time_zone_default")) %>
                         <script type="text/javascript">
                         	$("#client_time_zone").addClass("prevent_change");
                         </script>
          </td>
      </table>
      <div class="user_info_add">
        <p><%= I18n.t("client.user_information") %>▼</p>
        <input id="tags" placeholder="<%= I18n.t('client.user_search') %>" maxlength="255" class = "prevent_change"/>
      </div>
	  <div id="user_list_form">
      <table id="user_list" class="user_add">
        <thead>
        <tr>
          <th width="170">&nbsp;</th>
          <th width="240">&nbsp;</th>
          <th width="80">&nbsp;</th>
          <th style="width: 70px;">
            <div style="width: 70px;"><small><%= I18n.t("client.delete") %></small></div>
          </th>
        </tr>
        </thead>
        <% @client.client_users.active.each do |client_user| %>
        	<%
        		user = client_user.user
        		if user.client?
        			company = Client.find(user.company_id).client_name
        		else
        			company = Agency.find(user.company_id).agency_name
        		end
        	%>
            <tr>
              <th><%= short_ja_name(user.username) %>(<%= short_en_name(company) %>)</th>
              <td><%= short_en_name(user.email) %></td>
              <td><%= user.role.role_name %></td>
              <td><input class='del_user' type="checkbox" name="del_user_<%= user.id %>">
                <input type="hidden" name="users_id[]" value="<%= user.id %>"></td>
            </tr>
        <% end %>
      </table>
      </div>


      <div class="submit_area">
        <input type="image" id="btn_submit" src="/assets/btn_done.gif">
        <%= link_to raw('<img align="right" alt="キャンセル" src="/assets/btn_cancel.gif">'), clients_path %>
      </div>
    </div>
<% end %>

app/views/clients/_client_info_form.html.erb
<%= form_for(@client, remote: true) do |f| %>
    <div class="regist_form">
      <table class="client_info">
        <tr>
          <th> <%= f.label t("client.client_name") %>  </th>
          <td colspan="2"><%= f.text_field :client_name, maxlength: 255, style: "width: 250px", class: "prevent_change" %></td>
        </tr>
        <tr>
          <th><div style="width: 180px;"><%= f.label t("client.roman_name") %></div></th>
          <td colspan="2"><%= f.text_field :roman_name, maxlength: 255, style: "width: 250px", class: "prevent_change" %>
          </td>
        </tr>

        <tr>
          <th><%= f.label t("client.tel") %>
            <td colspan="2"><%= f.text_field :tel, maxlength: 15, style: "width: 250px", class: "prevent_change" %>
            </td>
        </tr>
        <tr>
          <th>
            <%= f.label t("client.person_charge") %> </th>
          <td colspan="2"><%= f.text_field :person_charge, maxlength: 255, style: "width: 250px", class: "prevent_change" %>
          </td>
        </tr>
        <tr>
          <th><%= f.label t("client.person_sale") %>   </th>
            <td colspan="2"><%= f.text_field :person_sale, maxlength: 255, style: "width: 250px", class: "prevent_change" %>
            </td>
        </tr>
        <tr>
          <th>
            <%= f.label t("client.contract_flg.label") %> </th>
          <td style="width: 150px;"><%= f.radio_button :contract_flg, 0, {checked: @client.contract_flg.nil? || @client.contract_flg == "0" ? true : false, class: "prevent_change"} %> <%= I18n.t("client.contract_type.unrecovered") %></td>
          <td style="width: 150px;"> <%= f.radio_button :contract_flg, 1, { class: "prevent_change"} %> <%= I18n.t("client.contract_type.been_recovered") %>
          </td>
        </tr>
        <tr>
          <th><%= f.label t("client.contract_type.label") %></th>
          <td><div style="width: 200px;"><%= f.radio_button :contract_type, 0, {checked: @client.contract_type.nil? || @client.contract_type == "0" ? true : false, class: "prevent_change"} %> <%= I18n.t("client.contract_flg.standard_plan") %></div></td>
          <td><div style="width: 310px;"><%= f.radio_button :contract_type, 1, class: "prevent_change" %> <%= I18n.t("client.contract_flg.premium_plan") %></div>
          </td>
        </tr>
        <tr>
          <th><%= f.label t("client.time_zones") %></th>
          <td colspan="2">
                         <%= f.select(:time_zone, @time_zones.each_with_index.map {|name, index| [name, index+1]}, :prompt => I18n.t("client.time_zone_default")) %>
                         <script type="text/javascript">
                         	$("#client_time_zone").addClass("prevent_change");
                         </script>
          </td>
        </tr>
      </table>
      <div class="user_info_add">
        <p><%= I18n.t("client.user_information") %>▼</p>
        <input id="tags" placeholder="<%= I18n.t('client.user_search') %>" maxlength="255" class= "prevent_change"/>
      </div>
	  <div id="user_list_form">
      <table id="user_list" class="user_add">
        <thead>
        <tr>
          <th width="170">&nbsp;</th>
          <th width="240">&nbsp;</th>
          <th width="80">&nbsp;</th>
          <th width="70">
            <div style="width: 70px;"><small id="delete_label" style="display:none"><%= I18n.t("client.delete") %></small></div>
          </th>
        </tr>
        </thead>
      </table>
      </div>
      <div class="submit_area">
        <input type="image" id="btn_submit" src="/assets/btn_done.gif">
        <%= link_to raw('<img align="right" alt="キャンセル" src="/assets/btn_cancel.gif">'), clients_path %>
      </div>
    </div>
<% end %>

app/views/clients/create.js.erb
<% if @error == I18n.t("client.flash_messages.success") %>
	<% flash[:error] = @error %>
	location.href = "<%= clients_path(client_id: @client.id) %>";
<% else %>
	prevent_change = "1";
	$("#client_info").html("<%=j render 'client_info_form'%>");
	$("#user_list_form").html(user_list_html);
	$("#tags").autocomplete({
            source: list_user,
            select: function (event, ui) {
            	prevent_change = "1";
                $("#tags").val("");
                list_user.splice(list_user.indexOf(ui.item), 1);
                data = ui.item;
                $("#user_list").append("<tr><th>" + data.label + "(" + data.company + ")</th>" + "<td>" + data.email + "</td><td>" + data.role
                        + "</td><td><input type = 'hidden' name='users_id[]' value ='" + data.value +
                        "'><input class= 'del_user' type = 'checkbox' name='del_user_" + data.value + "'></td></tr>");
                $('#delete_label').css("display", "block");
                user_list_html = $("#user_list_form").html();
                $(this).blur();
                return false;
            },
            minLength: 0,
            focus: function (e, ui) {
                e.preventDefault();
                this.value = ui.item.label;
            }
        }).focus(function (event) {
                    $(this).autocomplete("search");
                });
<% end %>

app/views/clients/edit.html.erb
<% provide(:title, I18n.t("client.title.edit")) %>
<script type="text/javascript">
$(function(){
	prevent_change = "<%= @prevent %>";
	$(".prevent_change").change(function(){
		prevent_change = "1"
	})
})
</script>
<%= stylesheet_link_tag "css/common" %>
<%= render "layouts/prevent_change_page_edit" %>
<% content_for :sidebar do %>
	<%= render partial: "layouts/sidebar", locals: {object: @clients} %>
<% end %>
<p class="h2"><%= I18n.t("client.crumb_edit") %></p>
<div id="client_info">
  <%= render "client_info_edit_form" %>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        list_ignore_user = [];
        list_user = [];
        user_list_html = $("#user_list_form").html();
        <% @client.client_users.active.each do |client_user|%>
        list_ignore_user.push({"value": "<%= client_user.user.id %>"});
        <% end %>
        <% User.active.order_by_roman_name.where('role_id != ?',1).each do |user|%>
        <%
        if user.client?
          company = Client.find(user.company_id).client_name
        else
        	company = Agency.find(user.company_id).agency_name
        end
        %>
        list_user.push({"label": "<%= short_ja_name(user.username) %>", "value": "<%= user.id %>", "email": "<%= short_en_name(user.email) %>", "role": "<%= user.role.role_name %>", "company": "<%= short_ja_name(company) %>"});
        <% end %>
        $(list_ignore_user).each(function (i, data) {
            list_user.splice(index_of(list_user, data.value), 1);
        });
        $("#tags").autocomplete({
            source: list_user,
            select: function (event, ui) {
            	prevent_change = "1";
                $("#tags").val("");
                list_user.splice(list_user.indexOf(ui.item), 1);
                data = ui.item;
                $("#user_list").append("<tr><th>" + data.label + "(" + data.company + ")</th>" + "<td>" + data.email + "</td><td>" + data.role
                        + "</td><td><input type = 'hidden' name='users_id[]' value ='" + data.value +
                        "'><input class= 'del_user' type = 'checkbox' name='del_user_" + data.value + "'></td></tr>");
				user_list_html = $("#user_list_form").html();
                $(this).blur();
                return false;
            },
            minLength: 0,
            focus: function (e, ui) {
                e.preventDefault();
                this.value = ui.item.label;
            }
        }).focus(function (event) {
                    $(this).autocomplete("search");
                    $("#tags").val("");
                    event.preventDefault();
                });
        $(document).on('click', ".del_user", function(){
        	if ($(this).is(':checked')){
        		$(this).attr("checked","checked");
        		user_list_html = $("#user_list_form").html();
        	}else{
        		$(this).removeAttr("checked");
        		user_list_html = $("#user_list_form").html();
        	}
        });
    });
</script>

app/views/clients/index.html.erb
<% provide(:title, I18n.t("client.title.list")) %>
<%= stylesheet_link_tag "css/common" %>
<style type="text/css">
	.flexigrid div.bDiv td {
		border-right : none;
	}
</style>
<% if flash[:error] %>
    <div><%= flash[:error] %></div>
<% end %>

<% if @clients.count > 0 %>
    <% content_for :sidebar do %>
        <%= render partial: "layouts/sidebar", locals: {object: @clients} %>
    <% end %>
    <div title="<%= @client.client_name %>"><p class="h2" id="client_name"><%= short_ja_name(@client.client_name) %></p></div>
    <% if current_user.super? %>
        <img id='create_promotion' src="/assets/btn_promotion_regist.gif" onclick="create()" style="display: none">
    <% end %>
    <table class="newTable06 fixTable d-none" style="display: none"></table>
    <script type="text/javascript">
        $(".newTable06").flexigrid({
            url: "<%= get_promotions_list_clients_path %>" + "?id=<%= @client.id if @client %>",
            dataType: 'json',
            colModel: [
                {display: '<%= I18n.t("Promotion Name") %>', name: 'promotion_name', width: 'auto', sortable: false, align: 'left'}
            ],
            sortname: "promotion_name",
            sortorder: "desc",
            usepager: true,
            title: 'Promotion Name',
            useRp: true,
            rp: 10,
            showTableToggleBtn: true,
            resizable: false,
            optionGet: "1",
            pagetext: "<%= I18n.t("Page") %>",
			outof: "<%= I18n.t("of") %>", 
            onSuccess: function () {
                tableResize();
                checkrow();
            }
        });
        function checkrow(com, grid) {
            var i = 0;
            $('.newTable06 tr', grid).each(function () {
                i++;
            });
            if (i == 0)
                $('#create_promotion').css('display', '');
            else
                $('#create_promotion').css('display', 'none');

        }
        function create() {
            var client_id = $('a[class="client_name current"]').attr('id');
            ajaxCommon('<%= new_promotion_path() %>?client_id=' + client_id, '', '', '', '#inner');
        }
    </script>
<% else %>
    <h2 id="client_name">No data</h2>
<% end %>

app/views/clients/new.html.erb
<% provide(:title, I18n.t("client.title.add")) %>
<script type="text/javascript">
$(function(){
	prevent_change = "<%= @prevent %>";
	$(".prevent_change").change(function(){
		prevent_change = "1"
	})
})
</script>
<%= stylesheet_link_tag "css/common" %>
<p class="h2"><%= I18n.t("client.crumb_add") %></p>
<%= render "layouts/prevent_change_page_new" %>
<% content_for :sidebar do %>
	<%= render partial: "layouts/sidebar", locals: {object: @clients} %>
<% end %>
<div id="client_info">
  <%= render "client_info_form" %>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        list_user = [];
        user_list_html = $("#user_list_form").html();
        <% User.active.order_by_roman_name.where('role_id != ?',1).each do |user|%>
        <%
        if user.client?
          company = Client.find(user.company_id).client_name
        else
        	company = Agency.find(user.company_id).agency_name
        end
        %>
        list_user.push({"label": "<%= short_ja_name(user.username) %>", "value": "<%= user.id %>", "email": "<%= short_en_name(user.email) %>", "role": "<%= user.role.role_name %>", "company": "<%= short_ja_name(company) %>"});
        <% end %>
        $("#tags").autocomplete({
            source: list_user,
            select: function (event, ui) {
            	prevent_change = "1";
                $("#tags").val("");
                list_user.splice(list_user.indexOf(ui.item), 1);
                data = ui.item;
                $("#user_list").append("<tr><th>" + data.label + "(" + data.company + ")</th>" + "<td>" + data.email + "</td><td>" + data.role
                        + "</td><td><input type = 'hidden' name='users_id[]' value ='" + data.value +
                        "'><input class= 'del_user' type = 'checkbox' name='del_user_" + data.value + "'></td></tr>");
                $('#delete_label').css("display", "block");
                user_list_html = $("#user_list_form").html();
                $(this).blur();
                return false;
            },
            minLength: 0,
            focus: function (e, ui) {
                e.preventDefault();
                this.value = ui.item.label;
            }
        }).focus(function (event) {
                    $(this).autocomplete("search");
                });
        $(document).on('click', ".del_user", function(){
        	if ($(this).is(':checked')){
        		$(this).attr("checked","checked");
        		user_list_html = $("#user_list_form").html();
        	}else{
        		$(this).removeAttr("checked");
        		user_list_html = $("#user_list_form").html();
        	}
        });
    });
</script>

app/views/clients/show.html.erb
<% provide(:title, I18n.t("client.title.show")) %>
<h1>Listing clients</h1>
<%= link_to 'New Client', new_client_path %>
<table id="paging" style="display:none"></table>
<script type="text/javascript">
	$("#paging").flexigrid({
		url: "<%= get_promotions_list_clients_path %>",
		dataType: 'json',
		colModel : [
			{display: 'promotion_name', name : 'promotion_name', width : 'auto', sortable : false, align: 'center'}
			],
	    sortname: "promotion_name",
        sortorder: "desc",
		usepager: true,
		title: 'Promotion Name',
		useRp: true,
		rp: 15,
		showTableToggleBtn: true,
        resizable : false,
        optionGet : "5",
        onSuccess: function() {
            tableResize();
        },
		height: 200
	});
</script>

app/views/clients/update.js.erb
<% if @error == I18n.t("client.flash_messages.update") %>
	<% flash[:error] = @error %>
	location.href = "<%= clients_path(client_id: @client.id) %>";
<% else %>
	prevent_change = "1"
	$("#client_info").html("<%=j render 'client_info_edit_form'%>");
	$("#user_list_form").html(user_list_html);
	$("#tags").autocomplete({
            source: list_user,
            select: function (event, ui) {
            	prevent_change = "1";
                $("#tags").val("");
                list_user.splice(list_user.indexOf(ui.item), 1);
                data = ui.item;
                $("#user_list").append("<tr><th>" + data.label + "(" + data.company + ")</th>" + "<td>" + data.email + "</td><td>" + data.role
                        + "</td><td><input type = 'hidden' name='users_id[]' value ='" + data.value +
                        "'><input class= 'del_user' type = 'checkbox' name='del_user_" + data.value + "'></td></tr>");
				user_list_html = $("#user_list_form").html();
                $(this).blur();
                return false;
            },
            minLength: 0,
            focus: function (e, ui) {
                e.preventDefault();
                this.value = ui.item.label;
            }
        }).focus(function (event) {
                    $(this).autocomplete("search");
                    $("#tags").val("");
                    event.preventDefault();
                });
<% end %>