config/routes.rb
PolarisManage::Application.routes.draw do
  resources :promotions do
    get "search", on: :collection
    post "delete_promotion", to: "promotions#delete_promotion", on: :collection
    post "get_promotions_report", on: :collection
    post "download_csv", on: :collection
    post "change_data", on: :collection
    get "promotion_table", on: :collection
  end
  resources :users do
    get "change_lang", on: :collection
    post "get_users_list", on: :collection
    get "search", on: :collection
    post "enable_disable_user", on: :collection
    post "change_company_list", on: :collection
  end
  resources :roles
  resources :conversions do
    get "get_tag", on: :member
    post "change_current_id", on: :collection
  end
  resources :clients do
    post "del_client", to: "clients#del_client", on: :collection
    post "get_promotions_list", on: :collection
  end
  resources :agencies do
    post "get_agencies_list", on: :collection
  end
  resources :sessions, only: [:new, :create] do
    post "resend_password", on: :collection
  end
  match "/signin",  to: "sessions#new"
  match "/signout", to: "sessions#signout"
  root to: "clients#index"
  resources :accounts, only: [:new, :create, :edit, :update] do
    post "change_medias_list", on: :collection
  end
  resources :click_logs, only: [:index] do
    post "get_logs_list", on: :collection
    post "download_csv", on: :collection
    post "change_accounts_list", on: :collection
  end
  resources :conversion_promotion_logs, only: [:index] do
    post "get_conversion_logs_list", on: :collection 
    post "download_csv", on: :collection
    post "change_accounts_list", on: :collection
  end
  resources :url_settings do
    post "get_urls_list", on: :collection
    post "download_csv", on: :collection
    get "download_template", on: :collection
  end
  resources :background_jobs do
    get "upload", on: :collection
    get "download", on: :collection
    get "inprogress", on: :collection
    post "notification", on: :collection
    get "download_file", on: :collection
    post "kill_job", to: "background_jobs#kill_job", on: :collection
  end
  resources :imports
  mount Resque::Server, at: '/resque'

end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div id="footerInner">
    <ul>
      <li><a href="<%= I18n.t("footer.terms_and_conditions_link")%>"><%= I18n.t("footer.terms_and_conditions")%></a></li>
      <li><a href="<%= I18n.t("footer.privacy_policy_link")%>"><%= I18n.t("footer.privacy_policy")%></a></li>
      <li><a href="<%= I18n.t("footer.corporate_information_link")%>"><%= I18n.t("footer.corporate_information")%></a></li>
    </ul>
  </div><!-- /#footerInner end -->
  <div id="copyright">
    <p>Copyright &copy; Septeni Co.,Ltd All Right Reserved</p>
    <a href="<%= I18n.t("footer.corporate_link")%>"><img src="/assets/logo_septeni.jpg" /></a></p>
  </div><!-- /#copyright end -->
</div><!-- /#footer end -->

app/views/layouts/_login.html.erb
<script type="text/javascript">//アコーディオン

$(document).ready(function () {
    $("#recaptcha_response_field").attr("tabindex", "7");
    $("#change_language").change(function () {
        $.cookie("locale", $(this).val());
        location.href = "<%= signin_path %>"
    })
    //hack google display captcha
    $("#recaptcha_reload_btn").remove();
    $("#recaptcha_switch_audio_btn").remove();
    $("#recaptcha_response_field").attr("style","width: 302px;");
    $("#recaptcha_switch_img_btn").remove();
    $("#recaptcha_whatsthis_btn").remove();
    $("#recaptcha_logo").remove();
    $("#recaptcha_privacy").remove();
    $("#recaptcha_table").attr("class", "");
    $('<p class="bold"><%= I18n.t("login.captcha")%></p>').insertBefore("#recaptcha_response_field");
    $("#recaptcha_area").attr("style", "margin-left:-5px");

    //end captcha google

    //----------------------------
    $('.accordion01').click(function () {
        $("#accordion01_inner").slideToggle('slow');
        $('#passwd').toggleClass("arrow1");
        $('#passwd').toggleClass("arrow2");
        if ($('#passwd').attr('class') == 'arrow1')
            $('#passwd').text('<%= I18n.t("login.forgor_pw")%>');
        else
            $('#passwd').text('<%= I18n.t("login.forgor_pw1")%>');

    })

    $('.accordion_close').toggle(
            function () {
            },
            function () {
            }

    );
});

</script>
<div id="sidebar">
  <div class="loginbox">
    <p class="title"><%= I18n.t("layout.login") %></p>

    <form action="/sessions" method="post">
      <label><span class="bold"><%= I18n.t("login.email") %></span><br/>
        <input type="text" name="session[email]" id="email" class="input-text" maxlength="255" tabindex="1"/></label>
      <br/>

      <p class="bold"><%= I18n.t("login.choose_lang.label") %></p>
      <select name="language" tabindex="2" id="change_language">
        <% if cookies[:locale] == "ja" %>
            <option value="ja" selected><%= I18n.t("login.choose_lang.ja") %>　</option>
        <% else %>
            <option value="ja"><%= I18n.t("login.choose_lang.ja") %>　</option>
        <% end %>
        <% if cookies[:locale] == "en" %>
            <option value="en" selected><%= I18n.t("login.choose_lang.en") %>　</option>
        <% else %>
            <option value="en"><%= I18n.t("login.choose_lang.en") %>　</option>
        <% end %>
      </select><br/>
      <label><span class="bold"><%= I18n.t("login.pw") %></span><br/>
        <input type="password" name="session[password]" id="password" class="input-text" maxlength="255" tabindex="3"/></label>
      <input type="image" id="btn_submit" src="/assets/btn_login.gif" tabindex="4">
      <% if @errors && @errors.count > 0 %>
          <% @errors.each do |error| %>
              <p class="error"><%= error %> </p>
          <% end %>
      <% end %>

    </form>

    <div class="accordion01 ta-c clearfix">
      <p tabindex="5" id="passwd" class="arrow1"><%= I18n.t("login.forgor_pw") %></p></div>


  </div>
  <!-- /.loginbox end -->
  <% if (@form_errors && @form_errors.count > 0) || flash[:send_success] || flash[:email_empty] %>
      <div id="accordion01_inner" class="loginbox_more">
  <% else %>
      <div id="accordion01_inner" class="loginbox_more" style="display:none">
  <% end %>
  <p class="account_txt01"><%= I18n.t("login.notice") %></p>
  <% if  flash[:email_empty] %>
      <div><span class="text-validationError"><%= flash[:email_empty] %></span></div>
  <% end %>
  <div class="span6 offset3">
    <%= form_tag(resend_password_sessions_path, method: :post) do %>
        <p class="bold"><%= label_tag I18n.t("login.email") %></p>
        <%= text_field_tag "email", @email, maxlength: 255, style: "width: 100%;", tabindex: 6 %>
        <%= recaptcha_tags display: {lang: "#{I18n.locale}", theme: "clean"} %>
        <input type="image" id="Send" src="/assets/btn_submit.gif" tabindex="8">
    <% end %>
    <% if @form_errors && @form_errors.count > 0 %>
        <% @form_errors.each do |error| %>
            <div>
              <% error = error.split(I18n.t("login.split")) %>
              <% error.each do |e| %>
                  <div><span class="text-validationError"><%= e + I18n.t("login.split") %></span></div>
              <% end %>
            </div>
        <% end %>
        <script type="text/javascript">
            $("#resend_password_form").show();
        </script>
    <% end %>
    <div><%= flash[:send_success] %></div>
  </div>
  </div>
  </div>

app/views/layouts/_option_cv_checkall.html.erb
<div class="box03">
  <p class="box3_txt"><div id="redisplay_all"><%= I18n.t("cv_logs.show_all")%></div>
  <!-- チェックボックス -->
  <div class="check-group clearfix">
    <table width="90%">
      <% Settings.cv_options_part1.each_with_index do |option, index|%>
      <tr>
        <td class="check_txt"><%= I18n.t("cv_logs.#{option}") %></td>
        <td align=right>
          <%= link_to image_tag("/assets/btn_box_dl.gif"), "javascript:void(0)", id: "cv_logs_#{index}", onclick: "update_cookie('#{index}',this)"%>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
  <!-- /チェックボックス -->
</div>
<div class="box01">
  <p class="box3_txt">&nbsp;</p>
  <!-- チェックボックス -->
  <div class="check-group clearfix">
    <table width="90%">

      <% Settings.cv_options_part2.each_with_index do |option, index|%>
      <tr>
        <td class="check_txt"><%= I18n.t("cv_logs.#{option}") %></td>
        <td align=right>
          <%= link_to image_tag("/assets/btn_box_dl.gif"), "javascript:void(0)", onclick: "update_cookie('#{index+12}',this)"%>
        </td>
      </tr>
      <% end %>
      <tr>
        <td class="check_txt"><%= I18n.t("cv_logs.error_log_view")%></td>
        <td align=center >
          <input type="checkbox" name="error_table" id="error_table" checked="checked">
        </td>
      </tr>
    </table>
    <!-- /チェックボックス -->
  </div>
</div>

<div class="box01">
  <p class="box3_txt">&nbsp;</p>
  <!-- チェックボックス -->
  <div class="check-group clearfix">
    <table width="90%">

      <% Settings.cv_options_part2.each_with_index do |option, index|%>
      <tr>
        <td class="check_txt"><%= I18n.t("cv_logs.#{option}") %></td>
        <td align=right>
          <%= link_to image_tag("/assets/btn_box_dl.gif"), "javascript:void(0)", onclick: "update_cookie('#{index+12}',this)"%>
        </td>
      </tr>
      <% end %>
      <tr>
        <td class="check_txt"><%= I18n.t("cv_logs.error_log_view")%></td>
        <td align=center >
          <input type="checkbox" name="error_table" id="error_table" checked="checked">
        </td>
      </tr>
    </table>
    <!-- /チェックボックス -->
  </div>
</div>
</div>

app/views/layouts/_option_cv_default.html.erb
<div class="box03">
  <p class="box3_txt"><div id="display_all"><%= I18n.t("cv_logs.show_all")%></div></p>
  <!-- チェックボックス -->
  <div class="check-group clearfix">
    <table width="90%">
      <% Settings.cv_options_part1.each_with_index do |option, index|%>
      <tr>
        <td class="check_txt"><%= I18n.t("cv_logs.#{option}") %></td>
        <td align=right>
          <%= link_to cookies[:cv_options][index] == "0" ? image_tag("/assets/btn_box_add.gif") : image_tag("/assets/btn_box_dl.gif"), "javascript:void(0)", id: "cv_logs_#{index}", onclick: "update_cookie('#{index}',this)"%>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
  <!-- /チェックボックス -->
</div>
<div class="box01">
  <p class="box3_txt">&nbsp;</p>
  <!-- チェックボックス -->
  <div class="check-group clearfix">
    <table width="90%">

      <% Settings.cv_options_part2.each_with_index do |option, index|%>
      <tr>
        <td class="check_txt"><%= I18n.t("cv_logs.#{option}") %></td>
        <td align=right>
          <%= link_to cookies[:cv_options][index+12] == "0" ? image_tag("/assets/btn_box_add.gif") : image_tag("/assets/btn_box_dl.gif"), "javascript:void(0)", onclick: "update_cookie('#{index+12}',this)"%>
        </td>
      </tr>
      <% end %>
      <tr>
        <td class="check_txt"><%= I18n.t("cv_logs.error_log_view")%></td>
        <td align=center >
          <input type="checkbox" name="error_table" id="error_table" checked="checked">
        </td>
      </tr>
    </table>
    <!-- /チェックボックス -->
  </div>
</div>

<div class="box01">
  <p class="box3_txt">&nbsp;</p>
  <!-- チェックボックス -->
  <div class="check-group clearfix">
    <table width="90%">

      <% Settings.cv_options_part2.each_with_index do |option, index|%>
      <tr>
        <td class="check_txt"><%= I18n.t("cv_logs.#{option}") %></td>
        <td align=right>
          <%= link_to cookies[:cv_options][index+12] == "0" ? image_tag("/assets/btn_box_add.gif") : image_tag("/assets/btn_box_dl.gif"), "javascript:void(0)", onclick: "update_cookie('#{index+12}',this)"%>
        </td>
      </tr>
      <% end %>
      <tr>
        <td class="check_txt"><%= I18n.t("cv_logs.error_log_view")%></td>
        <td align=center >
          <input type="checkbox" name="error_table" id="error_table" checked="checked">
        </td>
      </tr>
    </table>
    <!-- /チェックボックス -->
  </div>
</div>

app/views/layouts/_option_cv_log_page.html.erb
<div style='display:none'>
<div id="inline_cv_logs">
<div class="f_box">
<p class="f_box_title"><%= I18n.t("cv_logs.label")%></p>
<p class="f_category_title1"><%= I18n.t("cv_logs.display_item")%></p>
<div id="page1">
<div id="current_box">
<div class="box03">
  <p class="box3_txt"><div id="display_all"><%= I18n.t("cv_logs.show_all")%></div></p>
  <!-- チェックボックス -->
  <div class="check-group clearfix">
    <table width="90%">
      <% Settings.cv_options_part1.each_with_index do |option, index|%>
      <tr>
        <td class="check_txt"><%= I18n.t("cv_logs.#{option}") %></td>
        <td align=right>
          <%= link_to cookies[:cv_options][index] == "0" ? image_tag("/assets/btn_box_add.gif") : image_tag("/assets/btn_box_dl.gif"), "javascript:void(0)", id: "cv_logs_#{index}", onclick: "update_cookie('#{index}',this)"%>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
  <!-- /チェックボックス -->
</div>
<div class="box01">
  <p class="box3_txt">&nbsp;</p>
  <!-- チェックボックス -->
  <div class="check-group clearfix">
    <table width="90%">

      <% Settings.cv_options_part2.each_with_index do |option, index|%>
      <tr>
        <td class="check_txt"><%= I18n.t("cv_logs.#{option}") %></td>
        <td align=right>
          <%= link_to cookies[:cv_options][index+12] == "0" ? image_tag("/assets/btn_box_add.gif") : image_tag("/assets/btn_box_dl.gif"), "javascript:void(0)", onclick: "update_cookie('#{index+12}',this)"%>
        </td>
      </tr>
      <% end %>
      <tr>
        <td class="check_txt"><%= I18n.t("cv_logs.error_log_view")%></td>
        <td align=center >
          <input type="checkbox" name="error_table" id="error_table" checked="checked">
        </td>
      </tr>
    </table>
    <!-- /チェックボックス -->
  </div>
</div>


</div>

</div>
<div class="submit_area">
  <button id="change_cookie" style="border: 0px"><img src="/assets/btn_done.gif" alt="完成"></button>
  <button id="not_change_cookie" style="border: 0px"><img src="/assets/btn_cancel.gif" alt="完成"></button>
</div>
</div>
</div>
</div>
<script>
    $(document).ready(function(){
        $(".inline_cv_logs").colorbox({inline:true, width:"710", height:"650" });
    });
</script>

app/views/layouts/_option_log_page.html.erb
<div style='display:none'>
<div id="inline_logs">
<div class="f_box">
<p class="f_box_title"><%= I18n.t("click_logs.label")%></p>
<p class="f_category_title1"><%= I18n.t("click_logs.display_item")%></p>
<div class="box02">
  <ul id="tab_logs">
    <li class="present"><p class="f_arrow"><%= I18n.t("click_logs.usually")%></p></li>
  </ul>
</div>
<div id="page1">
<div class="box031">
  <p class="box3_txt">
  	<div id="display_all"><%= I18n.t("click_logs.show_all")%></div></p>
	  <!-- チェックボックス -->
  <div class="check-group clearfix">
    <table width="90%">
      <% Settings.click_options.each_with_index do |option, index| %>
      <tr>
        <td class="check_txt"><%= I18n.t("click_logs.#{option}")%></td>
         <td align=right>
            <%= link_to cookies[:coptions][index] == "0" ? image_tag("/assets/btn_box_add.gif") : image_tag("/assets/btn_box_dl.gif"), "javascript:void(0)", onclick: "update_cookie('#{index}',this)"%>
          </td>
      </tr>
      <% end %>
      <tr>
        <td class="check_txt"><%= I18n.t("click_logs.error_log_view")%></td>
        <td align=right>
          <input type="checkbox" name="error_table" id="error_table" checked="checked">
        </td>
      </tr>
      
    </table>
  </div>
  <!-- /チェックボックス -->
</div>

</div>

<div id="page11" style="display: none">
<div class="box031">
  <p class="box3_txt">
  	<div id="display_all"><%= I18n.t("click_logs.show_all")%></div>
  	 </p>
  <!-- チェックボックス -->
  <div class="check-group clearfix">
    <table width="90%">
      <% Settings.click_options.each_with_index do |option, index| %>
      <tr>
        <td class="check_txt"><%= I18n.t("click_logs.#{option}")%></td>
         <td align=right>
            <%= link_to cookies[:coptions][index] == "0" ? image_tag("/assets/btn_box_add.gif") : image_tag("/assets/btn_box_dl.gif"), "javascript:void(0)", onclick: "update_cookie('#{index}',this)"%>
          </td>
      </tr>
      <% end %>
      <tr>
        <td class="check_txt"><%= I18n.t("click_logs.error_log_view")%></td>
        <td align=right>
          <input type="checkbox" name="error_table" id="error_table" checked="checked">
        </td>
      </tr>
      
    </table>
  </div>
  <!-- /チェックボックス -->
</div>

</div>

<div id="page12" style="display: none">
<div class="box031">
  <p class="box3_txt">
  	<div id="display_all"><%= I18n.t("click_logs.show_all")%></div>
  </p>
  <!-- チェックボックス -->
  <div class="check-group clearfix">
    <table width="90%">
      <% Settings.click_options.each_with_index do |option, index| %>
      <tr>
        <td class="check_txt"><%= I18n.t("click_logs.#{option}")%></td>
         <td align=right>
            <%= link_to image_tag("/assets/btn_box_dl.gif"), "javascript:void(0)", onclick: "update_cookie('#{index}',this)"%>
          </td>
      </tr>
      <% end %>
      <tr>
        <td class="check_txt"><%= I18n.t("click_logs.error_log_view")%></td>
        <td align=right>
          <input type="checkbox" name="error_table" id="error_table" checked="checked">
        </td>
      </tr>
      
    </table>
  </div>
  <!-- /チェックボックス -->
</div>

</div>
<div class="submit_area2">
  <button id="change_cookie" style="border: 0px"><img src="/assets/btn_done.gif" alt="完成"></button>
  <button id="not_change_cookie" style="border: 0px"><img src="/assets/btn_cancel.gif" alt="完成"></button>
</div>
</div>
</div>
</div>
<script>
    $(document).ready(function(){
        $(".inline_logs").colorbox({inline:true, width:"515", height:"650" });
    });
var tab = {
init:
function(){
var tabs = this.setup.tabs;
var pages = this.setup.pages;

for(i=0; i<pages.length; i++) {
if(i !== 0) pages[i].style.display = 'none';
tabs[i].onclick = function(){tab.showpage(this); return false; };
}
},

showpage: function(obj){
var tabs = this.setup.tabs;
var pages = this.setup.pages;
var num;

for(num=0; num<tabs.length; num++) {
if(tabs[num] === obj) break;
}

for(var i=0; i<pages.length; i++) {
if(i == num) {
pages[num].style.display = 'block';
tabs[num].className = 'present';
}
else{
pages[i].style.display = 'none';
tabs[i].className = null;
}
}
}
}

// <![CDATA[

tab.setup = {
    tabs: document.getElementById('tab_logs').getElementsByTagName('li'),

    pages: [
        document.getElementById('page1')
    ]
} //オブジェクトをセット
tab.init(); //起動！
// ]]>
</script>

app/views/layouts/_popup_edit.html.erb
<p class="del_message" style="margin-top:20px;"><%= I18n.t("popup.edit_first") %><br /><%= I18n.t("popup.edit_second") %></p>

app/views/layouts/_popup_new.html.erb
<p class="del_message" style="margin-top:20px;"><%= I18n.t("popup.new_first") %><br /><%= I18n.t("popup.new_second") %></p>

app/views/layouts/_sidebar.html.erb
<% object = object.all unless object.class == Array %>
<div id="sidebar">
  <div id="clienetlist_box">
    <dl>
      <dt></dt>
      <dd>
        <div  id="searchform" name="searchform">
          <input type="text" placeholder="<%= I18n.t('client.user_search') %>" id="keywords" name="keywords" maxlength="255">
          <img id="searchBtn" name="searchBtn" alt="<%= I18n.t('client.user_search') %>" src="/assets/img_loupe.gif">
        </div>
      </dd>
    </dl>
    <div style="border-top:1px solid #c1c1c1;"></div>
    <% if params[:controller] == "clients" %>
    	<% if @client.id %>
	    	<script type="text/javascript">
	    	$(function() {
	    		$("#clients_list").scrollTo("#<%= @client.id if @client%>");
	    		
	    	});
	    	</script>
	    <% end %>
        <div id="clients_list">
          <table class="sidebar">
            <%
             if object && object.count >0
             object.each_with_index do |client, index| %>
                <tr>
                  <th class="edit"><%= link_to "", "#{edit_client_path(client)}", class: "edit", id: "edit#{client.id}" if current_user.super? %></th>
                  <% if params[:action] == "index" %>
                      <% if (params[:client_id] && client.id == params[:client_id].to_i) || (!params[:client_id] && index == 0) %>
                          <td><div style="width: 220px;"><%= link_to short_ja_name(client.client_name), "#{clients_path(client_id: client.id)}", class: "client_name current", title: "#{client.client_name}", id: "#{client.id}" %>
                         	<%= link_to short_ja_name(client.client_name), "#{clients_path(client_id: client.id)}", class: "client_name_search", id: "search#{client.id}" %></div>
                          </td>
                      <% else %>
                          <td><div style="width: 220px;"><%= link_to short_ja_name(client.client_name), "#{clients_path(client_id: client.id)}", class: "client_name", title: "#{client.client_name}", id: "#{client.id}" %>
								<%= link_to short_ja_name(client.client_name), "#{clients_path(client_id: client.id)}", class: "client_name_search", id: "search#{client.id}" %></div>
                          </td>
                      <% end %>
                  <% else %>
                      <% if (params[:id] && client.id == params[:id].to_i) || (!params[:id] && index == 0) %>

                          <td><div style="width: 220px;"><%= link_to short_ja_name(client.client_name), "#{clients_path(client_id: client.id)}", title: "#{client.client_name}", class: "client_name current", id: "#{client.id}" %></div></td>
                      <% else %>
                          <td><div style="width: 220px;"><%= link_to short_ja_name(client.client_name), "#{clients_path(client_id: client.id)}", title: "#{client.client_name}", class: "client_name", id: "#{client.id}" %></div></td>
                      <% end %>
                  <% end %>
                </tr>
            <% end 
            end %>
          </table>
        </div>
    <% elsif params[:controller] == "promotions" || params[:controller] == "click_logs" || params[:controller] == "conversion_promotion_logs" %>
        <div id="promotions_list">
          <table class="sidebar">
            <% object.each_with_index do |promotion, index| %>
                <tr>
                  <th class="edit"><%= link_to "", "#{edit_promotion_path(promotion)}?client_id=#{@client_id}", class: "edit", id: "edit#{promotion['id']}" if current_user.super? || current_user.agency? %></th>
                  <% if (params[:promotion_id] && promotion.id == params[:promotion_id].to_i) || (!params[:promotion_id] && index == 0) %>
                      <td><div style="width: 220px;">
                        <% if params[:controller] == "click_logs" %>
                            <%= link_to short_ja_name(promotion.promotion_name), "#{click_logs_path(promotion_id: promotion['id'])}", title: "#{promotion.promotion_name}", class: "promotion_name current", id: "#{promotion['id']}" %>
                        <% elsif params[:controller] == "conversion_promotion_logs" %>
                            <%= link_to short_ja_name(promotion.promotion_name), "#{conversion_promotion_logs_path(promotion_id: promotion.id)}", title: "#{promotion.promotion_name}", class: "promotion_name current", id: "#{promotion.id}" %>
                        <% else %>
                            <%= link_to short_ja_name(promotion.promotion_name), "#{promotions_path(promotion_id: promotion['id'], client_id: params[:client_id])}", title: "#{promotion.promotion_name}", class: "promotion_name current", id: "#{promotion['id']}" %>
                        <% end %>
                        </div>
                      </td>
                  <% else %>
                      <td>
                      	<div style="width: 220px;">
                        <% if params[:controller] == "click_logs" %>
                            <%= link_to short_ja_name(promotion.promotion_name), "#{click_logs_path(promotion_id: promotion['id'])}", title: "#{promotion.promotion_name}", class: "promotion_name", id: "#{promotion['id']}" %>
                        <% elsif params[:controller] == "conversion_promotion_logs" %>
                            <%= link_to short_ja_name(promotion.promotion_name), "#{conversion_promotion_logs_path(promotion_id: promotion.id)}", title: "#{promotion.promotion_name}", class: "promotion_name", id: "#{promotion.id}" %>
                        <% else %>
                            <%= link_to short_ja_name(promotion.promotion_name), "#{promotions_path(promotion_id: promotion['id'], client_id: params[:client_id])}", title: "#{promotion.promotion_name}", class: "promotion_name", id: "#{promotion['id']}" %>
                        <% end %></div></td>
                  <% end %>
                </tr>
            <% end %>
          </table>
        </div>
        <% unless (@promotion_id.blank? ? params[:promotion_id] : @promotion_id).blank? %>
        <script type="text/javascript">
    	$(function() {
    		$("#promotions_list").scrollTo("#<%= @promotion_id.blank? ? params[:promotion_id] : @promotion_id %>");
    	});
    	</script>
    	<% end %>
    <% elsif params[:controller] == "conversions" %>
        <div id="conversions_list">
          <table class="sidebar">
            <% 
            if object && object.count > 0
            object.each_with_index do |conversion, index| %>
                <tr>
                  <th class="edit"><%= link_to "", "#{edit_conversion_path(conversion)}?promotion_id=#{params[:promotion_id]}", class: "edit", id: "edit#{conversion.id}" if current_user.super? || current_user.agency? %></th>
                  <% if (params[:id] && conversion.id == params[:id].to_i) || (!params[:id] && index == 0) %>

                      <td><div style="width: 220px;"><%= link_to short_ja_name(conversion.conversion_name), "#{edit_conversion_path(conversion)}?promotion_id=#{params[:promotion_id]}", title: "#{conversion.conversion_name}", class: "conversion_name current", id: "#{conversion.id}" %></div></td>
                  <% else %>
                      <td><div style="width: 220px;"><%= link_to short_ja_name(conversion.conversion_name), "#{edit_conversion_path(conversion)}?promotion_id=#{params[:promotion_id]}", title: "#{conversion.conversion_name}", class: "conversion_name", id: "#{conversion.id}" %></div></td>
                  <% end %>
                </tr>
            <% end
            end%>
          </table>
        </div>
        <% unless params[:promotion_id].blank? %>
	        <script type="text/javascript">
	    	$(function() {
	    		$("#conversions_list").scrollTo("#<%= params[:promotion_id] %>");
	    	});
	    	</script>
	    <% end %>
    <% end %>
  </div>
  <% if params[:controller] == "clients" && current_user.super? %>
      <%= link_to raw('<img src="/assets/btn_client_regist.gif">'), "#{new_client_path}", class: "new_client_name" %>
  <% elsif (current_user.super? || current_user.agency?) && params[:controller] == "promotions" %>
      <%= link_to raw('<img src="/assets/btn_promotion_regist.gif">'), "#{new_promotion_path(client_id: @client_id)}", class: "new_promotion_name"  %>
  <% elsif (current_user.super? || current_user.agency?) && params[:controller] == "conversions" %>
      <%= link_to raw('<img src="/assets/btn_conversion_regist.gif">'), "#{new_conversion_path(client_id: @client_id, promotion_id: params[:promotion_id])}", class: "new_conversion_name" %>
  <% end %>
</div>