config/routes.rb
PolarisManage::Application.routes.draw do
  resources :promotions do
    get "search", on: :collection
    post "delete_promotion", to: "promotions#delete_promotion", on: :collection
    post "get_promotions_report", on: :collection
    post "download_csv", on: :collection
    post "change_data", on: :collection
    get "promotion_table", on: :collection
  end
  resources :users do
    get "change_lang", on: :collection
    post "get_users_list", on: :collection
    get "search", on: :collection
    post "enable_disable_user", on: :collection
    post "change_company_list", on: :collection
  end
  resources :roles
  resources :conversions do
    get "get_tag", on: :member
    post "change_current_id", on: :collection
  end
  resources :clients do
    post "del_client", to: "clients#del_client", on: :collection
    post "get_promotions_list", on: :collection
  end
  resources :agencies do
    post "get_agencies_list", on: :collection
  end
  resources :sessions, only: [:new, :create] do
    post "resend_password", on: :collection
  end
  match "/signin",  to: "sessions#new"
  match "/signout", to: "sessions#signout"
  root to: "clients#index"
  resources :accounts, only: [:new, :create, :edit, :update] do
    post "change_medias_list", on: :collection
  end
  resources :click_logs, only: [:index] do
    post "get_logs_list", on: :collection
    post "download_csv", on: :collection
    post "change_accounts_list", on: :collection
  end
  resources :conversion_promotion_logs, only: [:index] do
    post "get_conversion_logs_list", on: :collection 
    post "download_csv", on: :collection
    post "change_accounts_list", on: :collection
  end
  resources :url_settings do
    post "get_urls_list", on: :collection
    post "download_csv", on: :collection
    get "download_template", on: :collection
  end
  resources :background_jobs do
    get "upload", on: :collection
    get "download", on: :collection
    get "inprogress", on: :collection
    post "notification", on: :collection
    get "download_file", on: :collection
    post "kill_job", to: "background_jobs#kill_job", on: :collection
  end
  resources :imports
  mount Resque::Server, at: '/resque'

end

app/models/account.rb
class Account < ActiveRecord::Base
  VALID_NUMBER_REGEX = /^\d+$/
  VALID_FLOAT_REGEX = /^\d+\.\d+$/
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]{2,}+\z/i
  # VALID_ROMAN_NAME_REGEX = /[A-Z_\ \~\!\@\#\$\%\^\&\*\(\)\_\-\+\=\<\,\>\.\;\:\"\'\{\}0-9|\\\?\?\/a-z][A-Za-z_\ \~\!\@\#\$\%\^\&\*\(\)\_\-\+\=\<\,\>\.\;\:\"\'\{\}|\\\?\?\/\-0-9]*/
  VALID_ROMAN_NAME_REGEX = /^[\s!-~]+$/
  attr_accessible :margin, :create_user_id, :media_id, :promotion_id, :account_name, :roman_name,
                  :sync_account_id, :sync_account_pw, :sync_flg, :update_user_id, :media_category_id
  
  validates :promotion_id, presence: true
  validates :promotion_id, format: {with: VALID_NUMBER_REGEX}, if: -> account { account.promotion_id.present?}
  validates :media_id, presence: true
  validates :media_id, format: {with: VALID_NUMBER_REGEX}, if: -> account { account.media_id.present?}
  validates :margin, presence: true, length: {maximum: 255}
  validates_inclusion_of :margin, :in => 0..100000, if: -> account { account.margin.present?}
  validates :margin, :numericality => true, if: -> account { account.margin.present?}
  validates :sync_flg, presence: true,  length: {maximum: 1} , if: -> account { account.sync_flg.present?}
  validates :sync_flg, format: {with: VALID_NUMBER_REGEX}, if: -> account { account.sync_flg.present?}
  validates :account_name, presence: true, length: {maximum: 255}, uniqueness: {case_sensitive: false, scope: :promotion_id}
  validates :roman_name, presence: true, length: {maximum: 255}, uniqueness: {case_sensitive: false, scope: :promotion_id}
  validates :roman_name, format: {with: VALID_ROMAN_NAME_REGEX}, if: -> account { account.roman_name.present?}
  validates :sync_account_id, presence: true, length: {maximum: 255}, if: :check_sync
  validates :sync_account_id, format: {with: VALID_EMAIL_REGEX},if: :check_sync, if: -> account { account.sync_account_id.present?}
  validates :sync_account_pw, presence: true, length: {maximum: 255}, if: :check_sync
  validates :sync_account_pw, format: {with: VALID_ROMAN_NAME_REGEX}, if: :check_sync, if: -> account { account.sync_account_pw.present?}
  
  has_many :daily_summary_accounts
  has_many :daily_summary_acc_conversions
  belongs_to :promotion
  belongs_to :media
  
  def self.get_account_list promotion_id, media_list
    results = Hash.new
    accounts_list = Account.where(promotion_id: promotion_id)
    Settings.media_category.each do |category|
      media_list[category[1]+"_media"].each do |media|
        results["media"+media.id.to_s+"_account"] = Array.new
      end
    end
    
    accounts_list.each do |account|
      results["media"+account.media_id.to_s+"_account"] << account
    end
    results
  end

  private
  def check_sync
    sync_flg.to_i == 0 && media_category_id != 3
  end
end

app/controllers/accounts_controller.rb
require 'action_view'
class AccountsController < ApplicationController
  include ActionView::Helpers::SanitizeHelper
  before_filter :signed_in_user
  before_filter :must_super_agency
  before_filter :must_right_object, only: [:edit, :update]
  def new
    @account = Account.new
    @prevent = "0"
    @account.margin = Settings.account_cost_default
    @promotion_id = params[:promotion_id]
    @promotion = Promotion.find_by_id(@promotion_id)
    @medias = Media.active.where(media_category_id: 1)
    @client_id = @promotion.client.id
  end
  
  def edit
    @prevent = "0"
    @account = Account.find(params[:id])
    @account_name = Account.find(params[:id]).account_name
    @promotion_id = params[:promotion_id]
    @promotion = Promotion.find_by_id(@promotion_id)
    @client_id = @promotion.client.id
    @account_id = params[:id]
  end
  def update
    @prevent = "1"
    @account = Account.find(params[:id])
    @promotion_id = params[:promotion_id]
    @promotion = Promotion.find_by_id(@promotion_id)
    @client_id = @promotion.client_id
    params[:account][:roman_name] = sanitize(params[:account][:roman_name])
    params[:account][:account_name] = sanitize(params[:account][:account_name])
    @account.attributes = params[:account]
    @account.update_user_id = current_user.id
    if @account.sync_flg == Settings.account.sync_flg_active
      @account.sync_account_id = nil
      @account.sync_account_pw = nil
    end
    if @account.valid?
      ActiveRecord::Base.transaction do
        if @account.sync_account_pw != nil
          @account.sync_account_pw = AESCrypt.encrypt("TOPSCERETPOLARIS", @account.sync_account_pw)
        end
        if @account.save
          @margin = MarginManagement.new
          time = Time.new
          @margin.report_ymd = "#{time.year}#{time.month}#{time.day}"
          @margin.account_id = @account.id
          @margin.margin_rate = @account.margin
          @margin.create_user_id = current_user.id
          @margin.update_user_id = current_user.id
          if !@margin.save        
            flash[:error] = I18n.t("account.flash_messages.success_error")
            raise ActiveRecord::Rollback
          end
        end
      end
    else
      flash[:error] = I18n.t("account.flash_messages.success_error")
    end
    if flash[:error]
      @account_name = Account.find(params[:id]).account_name
      render :edit
    else
      flash[:error] = I18n.t("account.flash_messages.update")
      redirect_to promotions_path(promotion_id: @promotion_id, client_id: @promotion.client.id)
    end
  end
  def create
    @prevent = "1"
    params[:account][:roman_name] = sanitize(params[:account][:roman_name])
    params[:account][:account_name] = sanitize(params[:account][:account_name])
    @account = Account.new(params[:account])
    @medias = Media.active.where(media_category_id: @account.media_category_id)
    @promotion_id = params[:promotion_id]
    #get promotion by id
    @promotion = Promotion.find_by_id(@promotion_id)
    @client_id = @promotion.client_id
    @account.create_user_id = current_user.id
    if @account.sync_flg.to_i == 1
      @account.sync_account_id = nil
      @account.sync_account_pw = nil
    end
    
    if @account.valid?
      if @account.sync_account_pw != nil
        @account.sync_account_pw = AESCrypt.encrypt("TOPSCERETPOLARIS", @account.sync_account_pw)
      end
      ActiveRecord::Base.transaction do
        if @account.save
          @margin = MarginManagement.new
          time = Time.new
          @margin.report_ymd = "#{time.year}#{time.month}#{time.day}"
          @margin.account_id = @account.id
          @margin.margin_rate = @account.margin
          @margin.create_user_id = current_user.id
          if !@margin.save        
            flash[:error] = I18n.t("account.flash_messages.success_error")
            raise ActiveRecord::Rollback
          end
        end
      end
      if flash[:error]
        @account.media_id = params[:account][:media_id]
        render "new", promotion_id: @promotion_id
      else
        flash[:error] = I18n.t("account.flash_messages.success")
        redirect_to promotions_path(promotion_id: @promotion_id, client_id: @promotion.client_id)
      end
    else
      render "new", promotion_id: @promotion_id
    end
  end
  
  def change_medias_list
    render json: Media.active.where(media_category_id: params[:cid])
  end
  
  private
  def must_right_object
    @account = Account.find(params[:id])
    if current_user.agency? && !@account.promotion.client.client_users.find_by_user_id(current_user.id)
      redirect_to promotions_path(promotion_id: params[:promotion_id], client_id: @account.promotion.client.id)
    end
  end
end

app/views/accounts/_sync_box.html.erb
<tr>
  <th><%= f.label t("account.sync_account_id") %></th>
  <td style="width:330px;"><%= f.radio_button :sync_flg, 0, checked: true, onclick: "active_sync_box();", class: "prevent_change" %> <%= I18n.t("account.synchronism") %>
				            <%= f.radio_button :sync_flg, 1, onclick: "disable_sync_box();", class: "prevent_change" %> <%= I18n.t("account.fractured") %></td>
</tr>
<tr>
  <th></th>
  <td>
    <%= f.text_field :sync_account_id, maxlength: 255, style: "width: 280px", placeholder: " ID: ", class: "prevent_change" %>
  </td>
</tr>
<tr>
<th></th>
<td><%= f.password_field :sync_account_pw, maxlength: 255, value: @account.sync_account_pw, style: "width: 280px", placeholder: " PW: ", class: "prevent_change", autocomplete: "off" %>
<script type="text/javascript">
$(function(){
	prevent_change = "<%= @prevent %>";
	$(".prevent_change").change(function(){
		prevent_change = "1"
	})
})
</script>
</td>
</tr>

app/views/accounts/edit.html.erb
<% provide(:title, I18n.t("account.title.edit")) %>
<script type="text/javascript">
$(function(){
	prevent_change = "<%= @prevent %>";
	$(".prevent_change").change(function(){
		prevent_change = "1"
	})
})
</script>
<%= render "layouts/prevent_change_page_edit" %>
<%= stylesheet_link_tag "css/common" %>
<%= stylesheet_link_tag "css/accounts" %>
<ul class="contentNavi">
  <div class = "crumb">
    <li class="pre"><%= link_to short_ja_name(@promotion.client.client_name), clients_path(client_id: @promotion.client.id), title: @promotion.client.client_name %></li>
    <li>&gt;</li>
    <li class="pre"><%= link_to short_ja_name(@promotion.promotion_name), promotions_path(client_id: @promotion.client.id, promotion_id: @promotion.id), title: @promotion.promotion_name %>
    <li>&gt;</li>
    <li><%= I18n.t("account.crumb_edit") %>/<%= @account.media.media_name%> </li>
    <li>&gt;</li>
    <li><div title= "<%=@account_name%>"><%= short_ja_name(@account_name)%></div></li>
  </div>
</ul>
        
<% if flash[:success] %>
  <div><%= flash[:success] %></div>
<% end %>
<div id="account_form">
<%= form_for(@account) do |f| %>
    <div class="regist_form">
      <table class="account_info">
        <tbody>
        <tr>
          <th> <%= f.label t("account.media_category") %></th>
          <td colspan="2">
          	<input class="input-select prevent_change" type="hidden" name="media_category_id" id="media_category_id" value="<%= @account.media_category_id %>" />
          	<input class="input-select prevent_change" type="text" name="media_category" value="<%= t(Settings.media_category[@account.media_category_id])%>" disabled="disabled"></td>
        </tr>
        <tr>
          <th><%= f.label t("account.media") %></th>
          <td colspan="2">
          	<input class="input-select prevent_change" type="hidden" name="media_id" id="media_id" value="<%= @account.media_id %>" />
          	<input class="input-select prevent_change" type="text" name="xmedia_id" value="<%= @account.media.media_name%>" disabled="disabled">
            </td>
        </tr>
        <tr>
          <th ><%= f.label t("account.account_name") %></th>
          <td colspan="2"> <%= f.text_field :account_name, maxlength: 255, style: "width: 280px", class: "prevent_change" %>  </td>
        </tr>
        <tr>
          <th><%= f.label t("account.roman_name") %></th>
          <td colspan="2"><%= f.text_field :roman_name, maxlength: 255, style: "width: 280px", class: "prevent_change" %></td>
        </tr>
        <tr>
          <th><%= f.label I18n.t("account.margin") %></th>
          <td colspan="2"><%= I18n.t("account.input_data") %> &nbsp; × <%= f.text_field :margin, maxlength: 255, value: @account.margin, style: "width: 80px", class: "prevent_change" %></td><td id="percent" style="margin-left: -100px; position: absolute; margin-top: 13px;">%</td>
        </tr>
      </tbody>
      <tbody id="account_sync_box">
        <tr>
          <th><%= f.label t("account.sync_account_id") %></th>
          <td><%= f.radio_button :sync_flg, 1, checked: true, onclick: "active_sync_box();", class: "prevent_change" %> <%= I18n.t("account.synchronism") %></td>
          <td><%= f.radio_button :sync_flg, 0, onclick: "disable_sync_box();", class: "prevent_change" %> <%= I18n.t("account.fractured") %></td>
        </tr>
        <tr>
          <th></th>
          <td colspan="2" >
            <%= f.text_field :sync_account_id, maxlength: 255, style: "width: 280px", placeholder: " ID: ", class: "prevent_change" %>
          </td>
        </tr>
        <tr>
        <th></th>
        <td colspan="2">
        	<%= f.password_field :sync_account_pw, maxlength: 255, value: @account.sync_account_pw, style: "width: 280px", placeholder: " PW: ", class: "prevent_change", autocomplete: "off" %>
        </tr> 
        <tbody>
      </table>
      <div class="submit_area">
        <input type="image" id="btn_submit" src="/assets/btn_done.gif" >
        <%= link_to raw('<img align="right" alt="キャンセル" src="/assets/btn_cancel.gif">'), promotions_path(promotion_id: @promotion.id, client_id: @promotion.client.id) %>
      </div>
    </div>
    <input type="hidden" name="promotion_id" value="<%= @promotion.id %>">
<script type="text/javascript">
  <% if @account.errors[:margin].count > 0%>
    $("#percent").css("margin-top","3px");
  <% end %>
function disable_sync_box() {
	$("#account_sync_account_id").attr('disabled', true);
	$("#account_sync_account_pw").attr('disabled', true);
}
function active_sync_box() {
	$("#account_sync_account_id").removeAttr('disabled');
	$("#account_sync_account_pw").removeAttr('disabled');
}

jQuery(document).ready(function($) {
	$("#account_sync_flg_0").click(function() {
		if ($("#account_sync_flg_0").is(':checked')) {
			$("#account_sync_account_id").attr('disabled','disabled');
			$("#account_sync_account_pw").attr('disabled','disabled');
		}	
	});
	$("#account_sync_flg_1").click(function() {
		if ($("#account_sync_flg_1").is(':checked')) {
			$("#account_sync_account_id").removeAttr('disabled');
			$("#account_sync_account_pw").removeAttr('disabled');
		}	
	});
	
	
if ($("#media_category_id").val() < 3) {
    		$("#account_sync_box").html('<%=j render "sync_box", f: f%>');
    } else {
    	$("#account_sync_box").html("");
    }
    
if ($("#media_id").val() < 7) {
		$("#account_sync_box").html('<%=j render "sync_box", f:f%>');
} else {
	$("#account_sync_box").html("");
}
if ($("#account_sync_flg_1").is(':checked')) {
		
		$("#account_sync_account_id").attr('disabled','disabled');
		$("#account_sync_account_pw").attr('disabled','disabled');
	}	
});	
</script>    
<% end %>
</div>
	

app/views/accounts/new.html.erb
<% provide(:title, I18n.t("account.title.add")) %>
<script type="text/javascript">
$(function(){
	prevent_change = "<%= @prevent %>";
	$(".prevent_change").change(function(){
		prevent_change = "1"
	})
})
</script>
<%= render "layouts/prevent_change_page_new" %>
<%= stylesheet_link_tag "css/common" %>
<%= stylesheet_link_tag "css/accounts" %>
<ul class="contentNavi">
  <div class = "crumb">
    <li class="pre"><%= link_to short_ja_name(@promotion.client.client_name), clients_path(client_id: @promotion.client.id ), title: @promotion.client.client_name %></li>
    <li>&gt;</li>
    <li class="pre"><%= link_to short_ja_name(@promotion.promotion_name), promotions_path(client_id: @promotion.client.id, promotion_id: @promotion.id), title: @promotion.promotion_name %>
      <input type="hidden" name="promotion_id" value="<%= @promotion.id %>">
    </li>
    <li>&gt;</li>
    <li><%= I18n.t("account.crumb_add") %></li>
  </div>
</ul>
<% if flash[:success] %>
    <div><%= flash[:success] %></div>
<% end %>
<div id="account_form">
<%= form_for(@account) do |f| %>
    <input type="hidden" name="account[promotion_id]" value="<%= params[:promotion_id]%>" />
    <div class="regist_form">
      <table class="account_info">
        <tbody>
        <tr>
          <th> <%= f.label t("account.media_category") %></th>
          <td colspan="2"><%= f.select :media_category_id,
                         Settings.media_category.each_with_index.map {|name, index| [t(name[1]), index+1]} , {}, {class: "input-text prevent_change"} %>
          </td>
        </tr>
        <tr>
          <th><%= f.label t("account.media") %></th>
          <td colspan="2">
            <%= select_tag 'account[media_id]', options_from_collection_for_select(@medias, 'id', 'media_name', (@account.media_id) ? @account.media_id : ''), class: "input-select prevent_change" %>
          </td>
        </tr>
        <tr>
          <th><%= f.label t("account.account_name") %></th>
          <td colspan="2"> <%= f.text_field :account_name, maxlength: 255, style: "width: 280px", class: "prevent_change" %>  </td>
        </tr>
        <tr>
          <th><%= f.label t("account.roman_name") %></th>
          <td colspan="2"><%= f.text_field :roman_name, maxlength: 255, style: "width: 280px", class: "prevent_change" %></td>
        </tr>
        <tr>
          <th><%= f.label t("account.margin") %></th>
          <td colspan="2"><%= I18n.t("account.input_data") %> &nbsp; × <%= f.text_field :margin, maxlength: 255, value: @account.margin, style: "width: 80px; text-align: right", class: "prevent_change" %></td><td id="percent" style="margin-left: -80px; position: absolute; margin-top: 13px;">%</td>
        </tr>
        </tbody>
        <tbody id="account_sync_box">
        <tr>
          <th><%= f.label t("account.sync_account_id") %></th>
          <td><%= f.radio_button :sync_flg, 0, checked: true, onclick: "active_sync_box();", class: "prevent_change" %> <%= I18n.t("account.synchronism") %></td>
          <td style="width: 200px;"><%= f.radio_button :sync_flg, 1, onclick: "disable_sync_box();", class: "prevent_change" %> <%= I18n.t("account.fractured")%></td>
        </tr>
        <tr>
          <th></th>
          <td colspan="2">
            <%= f.text_field :sync_account_id, maxlength: 255, style: "width: 280px", placeholder: " ID: ", class: "prevent_change" %>
          </td>
        </tr>
        <tr>
        <th></th>
        <td colspan="2">
        	<%= f.password_field :sync_account_pw, maxlength: 255, style: "width: 280px", placeholder: " PW: ", class: "prevent_change", autocomplete: "off" %>
        </tr> 
      </tbody>
      </table>
      <div class="submit_area">
        <input type="image" id="btn_submit" src="/assets/btn_done.gif" class="prevent_change">
        <%= link_to raw('<img align="right" alt="キャンセル" src="/assets/btn_cancel.gif">'), promotions_path(promotion_id: @promotion.id, client_id: @promotion.client.id) %>
      </div>
      <input type="hidden" name="promotion_id" value="<%= @promotion.id %>">
<script type="text/javascript">
function disable_sync_box() {
	$("#account_sync_account_id").attr('disabled', true);
	$("#account_sync_account_pw").attr('disabled', true);
	$("#account_sync_account_pw").val('');
	$("#account_sync_account_id").val('');
}
function active_sync_box() {
	$("#account_sync_account_id").removeAttr('disabled');
	$("#account_sync_account_pw").removeAttr('disabled');
}
jQuery(document).ready(function($) {
  <% if @account.errors[:margin].count > 0%>
    $("#percent").css("margin-top","3px");
  <% end %>
	
	$("#account_media_category_id").change(function(){
		$.ajax({
	        type: "POST",
	        url: "<%= change_medias_list_accounts_path %>",
	        data: "cid=" + $(this).val(),
	        success: function (data) {
	            $("#account_media_id").html("");
	            for (var i = 0; i < data.length; i++) {
	                option = "<option value='" + data[i].id + "'>" + data[i].media_name + "</option>";
	                $("#account_media_id").append(option);
	            }
	        }
	    });
	    if ($(this).val() < 3) {
	    		if ($("#account_sync_box").html() == '')
            $("#account_sync_box").html('<%=j render "sync_box", f: f%>');
	    } else {
	    	$("#account_sync_box").html("");
	    }
	});
	
	$("#account_media_id").change(function() {
		if ($(this).val() < 7) {
	    		if ($("#account_sync_box").html() == '')
            $("#account_sync_box").html('<%=j render "sync_box", f: f%>');
	    } else {
	    	$("#account_sync_box").html("");
	    }
	});
	if ($("#account_media_category_id").val() < 3) {
    		$("#account_sync_box").html('<%=j render "sync_box", f: f%>');
    } else {
    	$("#account_sync_box").html("");
    }
    
    if ($("#account_media_id").val() < 7) {
    		//$("#account_sync_box").html('<%=j render "sync_box", f:f%>');
    } else {
    	$("#account_sync_box").html("");
    }
    if ($("#account_sync_flg_1").is(':checked')) {
    
    $("#account_sync_account_id").attr('disabled','disabled');
    $("#account_sync_account_pw").attr('disabled','disabled');
  } 
});

	
</script>      
<% end %>


</div>